version: "3"

services:
  arlocal:
    image: textury/arlocal:v1.1.35
    ports:
      - "1984:1984"

  pdns-service:
    build:
      context: .
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
        NODE_VERSION_SHORT: ${NODE_VERSION_SHORT:-18}
    environment:
      NODE_ENV: ${NODE_ENV:-dev}
      GATEWAY_HOST: arlocal
      GATEWAY_PORT: 1984
      GATEWAY_PROTOCOL: http
    ports:
      - "3000:3000"

  test-runner:
    build:
      context: .
      dockerfile: tests/integration/Dockerfile.integration
      args:
        NODE_VERSION: ${NODE_VERSION:-18.16.0}
    environment:
      HOST: pdns-service
      PORT: 3000
      GATEWAY_HOST: arlocal
      GATEWAY_PORT: 1984
      GATEWAY_PROTOCOL: http
    depends_on:
      - arlocal
      - pdns-service
